### ISSUE TITLE
CMake: FindPackage in Source Fails with CMakeLists

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#33] opened 2016-03-29 14:20 UTC
When building third party applications (in our case [this PIConGPU branch](https://github.com/theZiz/picongpu/commit/70c0593ac00a58db88fca3b6fcf72aeadf1660f6)) while pointing the isaac "install" to the source directory directly (instead of to the installed header location), the `CMakeLists.txt` seems to be chosen in `find_package(ISAAC)` over the `ISAACConfig.cmake`.

This causes the `cmake` command to fail as long as the `CMakeLists.txt` file is present.

**Comment by theZiz** [comment] 2016-03-29 14:57
Could you test replacing line 109 in the CMakeLists.txt of the isaac PIGonGPU branch from
```find_package(ISAAC 0.1.0 REQUIRED)```
to
```find_package(ISAAC 0.1.0 CONFIG REQUIRED)```
and tell me, whether he still complains if a CMakeLists.txt exists? Unfortunately I can't reproduce the error.

**Comment by ax3l** [comment] 2016-03-29 15:07
I am not exactly sure right now what this is doing ([CMake documentation](https://cmake.org/cmake/help/v3.0/command/find_package.html)) but
`find_package(ISAAC 0.1.0 CONFIG REQUIRED)`
is also not fixing it and enters `CMakeLists.txt` (and fails in line 75).

If one would like to use
`find_package(ISAAC 0.1.0 MODULE REQUIRED)`
then we would need a `FindISAAC.cmake` file instead (in CMAKE_MODULE_PATH). Idk which is the modern way to go.

**Comment by ax3l** [comment] 2016-03-29 15:08
To reproduce: I should mention that the root of isaac's source is in my `CMAKE_PREFIX_PATH`.

**Comment by theZiz** [comment] 2016-05-12 09:14
Should be fixed by moving the CMake Config files of ISAAC to the insitu library directory https://github.com/ComputationalRadiationPhysics/isaac/commit/e0cfb061e9a2d7b1b84e391dfa099221c3255102

**Closed by theZiz** 2016-05-12 09:14 UTC
Labels: bug
